pkzip mk3backs c:\video\kombat3\img\mkcity.*
pkzip mk3backs c:\video\kombat3\img\mksubraw.*
pkzip mk3backs c:\video\kombat3\img\mk3soul.*
pkzip mk3backs c:\video\kombat3\img\mkbank.*
pkzip mk3backs c:\video\kombat3\img\mkstreet.*
pkzip mk3backs c:\video\kombat3\img\mkbridge.*
pkzip mk3backs c:\video\kombat3\img\mkbell.*
pkzip mk3backs c:\video\kombat3\img\mkbell2.*
pkzip mk3backs c:\video\kombat3\img\mktemp2.*
pkzip mk3backs c:\video\kombat3\img\mkgrave.*
pkzip mk3backs c:\video\kombat3\img\mkthrone.*
pkzip mk3backs c:\video\kombat3\img\mkbalc2.*
pkzip mk3backs c:\video\kombat3\img\mkhidden.*
pkzip mk3backs c:\video\kombat3\img\mkshao1.*
pkzip mk3backs c:\video\kombat3\img\mkshao2.*
pkzip mk3backs c:\video\kombat3\img\mktext.*
pkzip mk3backs c:\video\kombat3\img\mkladder.*
pkzip mk3backs c:\video\kombat3\img\mkselect.*
pkzip mk3backs c:\video\kombat3\img\steelvs.*
pkzip mk3backs c:\video\kombat3\img\mk3buyin.*
pkzip mk3backs c:\video\kombat3\img\mk3coin.*
pkzip mk3backs c:\video\kombat3\img\mk3bio.*
pkzip mk3backs c:\video\kombat3\img\mk3end.*
pkzip mk3backs c:\video\kombat3\img\widebox.*

